title: Mohammud Yassine Jaffoo
name: MYJaffoo
email: yas360@hotmail.co.uk
description: Solutions Architect | Platform Engineer | DevOps Advocate

baseurl: "/blog"
url: ""

parallax_image_one: assets/images/laptop-landing.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/laptop-landing.jpg

project_one: "Creating and Hosting my website"
project_one_description: Building a SSL-enabled static website with a custom domain using GitHub Pages and Jekyll template. <br><br>Get started with GitHub Pages <a href="https://help.github.com/categories/github-pages-basics/">here</a>.<br>Get started with Jekyll <a href="https://jekyllrb.com/docs/home/">here</a>.
project_one_url: https://github.com/myjaffoo/myjaffoo.github.io
project_one_icon: location_on

project_two: Raspberry Pi Zero W
project_two_description: Coming soon!
project_two_url: https://github.com/myjaffoo
project_two_icon: photo_camera


project_three: Amazon Echo Dot
project_three_description: Coming Soon!
project_three_url: https://github.com/myjaffoo
project_three_icon: hotel


project_four: Fourth Project
project_four_description: Describe your project!
project_four_url: https://github.com/myjaffoo
project_four_icon: restaurant

portfolio_heading: Portfolio
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: amazonwebservices
  - name: apache
  - name: bitbucket
  - name: confluence
  - name: docker
  - name: gatling
  - name: git
  - name: github
  - name: gitlab
  - name: go
  - name: linux
  - name: mysql
  - name: nginx
  - name: nodejs
  - name: oracle
  - name: postgresql
  - name: python
  - name: redhat
  - name: redis
  - name: ruby
  - name: slack
  - name: tomcat
  - name: trello
  - name: twitter
  - name: ubuntu
  - name: vim

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/myjaffoo
medium: https://medium.com

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: http://localhost:4000/ #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: none # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
